/// <reference types="nativewind/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.

// Configuração adicional para suporte aos arquivos da pasta app
declare module "*.css" {
  const content: any;
  export default content;
}